name: CI
on: [push]

jobs:
  ci_build:
    name: Shellcheck
    runs-on: ubuntu-latest
    # Skip builds with "[ci skip]" in the commit
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
    - name: Install bats
      run: make bats-setup
    - name: Run bats
      run: ./test/bats/bin/bats test
